[package]
name = "flight-with-nexmark"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
arrow = "55.1.0"
arrow-flight = "55.1.0"
futures = "0.3.31"
nexmark = "0.2.0"
serde_json = "1"
tonic = "0.12.3"
prost = "0.13.5"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
async-stream = "0.3.6"
datafusion = "48.0.0"
datafusion-substrait = "48.0.0"
datafusion-common = "48.0.0"
parking_lot = "0.12.4"
datafusion-expr = "48.0.0"
datafusion-execution = "48.0.0"
datafusion-physical-expr = "48.0.0"
clap = { version = "4.0", features = ["derive"] }
