[rpi_cluster]
s1  ansible_host=192.168.2.80 ansible_user=picocluster
s2  ansible_host=192.168.2.81 ansible_user=picocluster
s3  ansible_host=192.168.2.82 ansible_user=picocluster
s4  ansible_host=192.168.2.83 ansible_user=picocluster
s5  ansible_host=192.168.2.84 ansible_user=picocluster
s6  ansible_host=192.168.2.85 ansible_user=picocluster
s7  ansible_host=192.168.2.86 ansible_user=picocluster
s8  ansible_host=192.168.2.87 ansible_user=picocluster
s9  ansible_host=192.168.2.88 ansible_user=picocluster
s10 ansible_host=192.168.2.89 ansible_user=picocluster
s11 ansible_host=192.168.2.90 ansible_user=picocluster
s12 ansible_host=192.168.2.91 ansible_user=picocluster
p1  ansible_host=192.168.2.92 ansible_user=picocluster
p2  ansible_host=192.168.2.93 ansible_user=picocluster
p3  ansible_host=192.168.2.94 ansible_user=picocluster
p4  ansible_host=192.168.2.95 ansible_user=picocluster
p5  ansible_host=192.168.2.96 ansible_user=picocluster
p6  ansible_host=192.168.2.97 ansible_user=picocluster
k1  ansible_host=192.168.2.98 ansible_user=picocluster
k2  ansible_host=192.168.2.99 ansible_user=picocluster
