class SourceNodeStatus:
    NOT_STARTED = "NOT_STARTED"
    GENERATING_DATA = "GENERATING_DATA"
    DATA_GENERATED = "DATA_GENERATED"
    SENDING_DATA = "SENDING_DATA"
    DONE = "DONE"


class SourceNodeActions:
    GENERATE_DATA = "GENERATE_DATA"
    SEND_DATA = "SEND_DATA"
    GET_STATUS = "GET_STATUS"
