[rpi_cluster]
source     ansible_host=192.168.2.80 ansible_user=picocluster
processing ansible_host=192.168.2.81 ansible_user=picocluster
sink       ansible_host=192.168.2.82 ansible_user=picocluster
